### ISSUE TITLE
Menu mit Tuttorial zur Datenpflege

### ISSUE THREAD

**Issue by stefangrotz** [CodeforKarlsruhe/direktvermarkter#13]
Es wäre sicher Sinnvoll ein Menu, z.B. dieses hier https://github.com/Turbo87/sidebar-v2 zu verwenden und dort ein Paar Details zur Datenpflege auf OSM zu dokumentieren. Außerdem kann man dort auf verwandte Projekte wie wo-ist-markt.de oder mundraub.org verlinken.

**Comment by thunfischtoast** [comment]
Meinst du eine Anleitung, wie man zB. mit dem OSM Online Editor sinnvoll Tags hinzufügt? Oder eine Art Frontend, womit man die Sachen direkt editieren kann?

**Comment by stefangrotz** [comment]
So ein Editor wäre natürlich großartig, aber ich wüsste nicht wie man so etwas umsetzen kann. Mit diesem Issue meine ich vorerst nur eine detailierte und leicht verständliche Anleitung wie man Hofläden und Automaten auf OSM einträgt.

**Comment by thunfischtoast** [comment]
Man müsste sich mit der API beschäftigen. StreetComplete (https://github.com/westnordost/StreetComplete) hat z.B. eine Lösung, mit der OSM-Updates direkt aus der App heraus gesendet werden kann, ohne dass man von Hand irgendwelche Tags bearbeiten muss. Bin mir aber nicht sicher, ob die ein Framework benutzen oder die Lösung selbst entwickelt haben. Ich weiß auch nicht, was leaflet da für Möglichkeiten bietet.

**Comment by h8h** [comment]
Wheelmap.org hat hier auch einen guten Ansatz. Man loggt sich über seinen OSM Account ein und wird wieder zurückgeleitet und kann sich dann in der bekannten Ansicht bewegen und neue Nodes hinzufügen. 

Die Sourcen sind auch offen [Wheelmap](https://github.com/sozialhelden/wheelmap/), aber es ist kein einfaches da durchzublicken.

Ich denke hier müssten man sich auch Oauth genauer anschauen.
