### ISSUE TITLE
Aktuellen Standort verwenden

### ISSUE THREAD

**Issue by lstangier** [CodeforKarlsruhe/direktvermarkter#20]
Es wäre besser für den Benutzer wenn die Karte sich automatisch auf den aktuellen Standort fokussiert und nicht auf Karlsruhe. Dies kann über eine Berechtigungsabfrage im Browser o.Ä. geschehen.

Auch wäre es meines Erachtens nach sinnvoll, eine Suchfunktion für Standorte einzubauen.

**Comment by stefangrotz** [comment]
Als fertige Lösung gibt es leaflet locatecontrol:
https://github.com/domoritz/leaflet-locatecontrol

Das Erkennt den Ort nur auf Wunsch, aber darauf kann man bestimmt aufbauen.

Ich weiß nur nicht wie gut das mit dem Permalink-Plugin zusammen spielt, das im Moment verwendet wird.

**Comment by mwkaufmann** [comment]
Ich hab das Feature implementiert. Siehe: https://github.com/mwkaufmann/direktvermarkter

Verwendet habe ich leaflet-locatecontrol. Falls noch was geändert werden soll, einfach Bescheid geben.

LG

**Comment by stefangrotz** [comment]
Hey, großartig, vielen Dank.  Ich habe das mal getestet, funktioniert super.

Das einzige was ich gerne noch ändern wirde bevor wir das Mergen ist dass sich durch die Integration von font awesome die Schriftart der Hs und As in den Pins verändert. Hast Du eine Idee warum das passiert? eigentlich habe ich überall im CSS eine andere Schriftart definiert.

Außerdem möchte ich Font-Awesome nicht von einer externen URL laden sondern als Datei hier im Artefakt haben und ich würde das Icon nach links oben setzen. Wie siehst Du das?

Ich schaue mir das morgen mal an. Vielen Dank noch mal!

**Comment by mwkaufmann** [comment]
Das Problem mit Fontawesome hängt wohl damit zusammen, dass die Pins die CSS-Klasse ".fa" verwenden. Diese wird auch durch fontawesome definiert... Da kommt es dann zur Kollision.

So wie es aussieht, wird die ".fa" Klasse durch das ExtraMarkers-Plugin angehängt.
Ich schaue mir an, wie wir das am elegantesten lösen können... 

Fontawesome ziehe ich dir auch noch interne Abhängigkeit ins Projekt rein, kein Problem.
Das Icon können wir gerne nach links oben setzen. Probiere ich gleich mal aus.

**Comment by mwkaufmann** [comment]
Alles klar, alle Änderungen durchgeführt. #23 kann kommen. :)

**Comment by stefangrotz** [comment]
Gemerged, Danke noch mal! Https wird ab jetzt immer erzwungen, weil locate wohl nur damit funktioniert.

**Comment by stefangrotz** [comment]
Klar, alle Treffen gibt es auf Meetup: https://www.meetup.com/de-DE/OK-Lab-Karlsruhe/

und auf https://codefor.de/karlsruhe/

Wennn Du magst kann ich dich auch in den Slack Channel von der OKFNDE einladen.
