### ISSUE TITLE
Auswertung Adressen

### ISSUE THREAD

**Issue by dooley** [CodeforKarlsruhe/direktvermarkter#25]
Öfter sind Adressen richtigerweise nicht mit addr:street, sondern mit addr:place erfasst. Im Moment wird in den Popups dann "undefined" angezeigt. In diesen Fällen sollte entsprechend addr:place statt addr:street zur Anzeige verwendet werden. 

https://www.openstreetmap.org/node/2189856258

**Comment by stefangrotz** [comment]
Das wird in der adress function in direktvermarkter.js definiert. Ich wollte die ganze funktion komplett umbauen, bin mir aber noch nicht ganz sicher wie. 

Außerdem wollte ich das ganze Popup in eine eigene Datei auslagern, weil das langsam echt unübersichtlich wird.

**Comment by dooley** [comment]
Ich würde nach kurzem Drüberschauen sagen, eigentlich ist das schon drin:
In Zeile https://github.com/CodeforKarlsruhe/direktvermarkter/blob/master/js/direktvermarkter.js#L237
müsste nur "addr:street" mit "addr:place" ersetzt werden, die Verzweigung passt ja.

**Comment by stefangrotz** [comment]
Addr:place ist zwei zeilen tiefer drinn, es gibt ja auch adressen mit Straße und place.

Ich wollte das viel allgemeiner definieren und eine funktion bauen die Testet ob ein Wert existiert und falls nicht einen leeren String zurück gibt. Mit dieser Funktion könnte man dann jeden Wert einfügen, dann kann man alle Werte in einem Fall abwickeln und hat kein hässliches undefined im Feld.

**Comment by dooley** [comment]
Äh, nein. Oder ich bin blind ;-)

>         else if (feature.properties["addr:place"]) {
>            var adresse = "<strong>Adresse:</strong><br>"
>                + feature.properties["addr:street"] + " " + feature.properties["addr:housenumber"]

Du frägst auf addr:place ab, verwendest dann aber addr:street. Das müsste so aussehen:

>         else if (feature.properties["addr:place"]) {
>            var adresse = "<strong>Adresse:</strong><br>"
>                + feature.properties["addr:place"] + " " + feature.properties["addr:housenumber"]

Und Adressen mit street UND place sind definitiv falsch eingetragen. Entweder/oder. Im Zweifel (wenn beide gesetzt sind), ist street maßgebend, deine Logik ist somit schon richtig.

**Comment by stefangrotz** [comment]
Wie gesagt, drei Zeilen Tiefer:

`            var adresse = "<strong>Adresse:</strong><br>"
                + feature.properties["addr:street"] + " " + feature.properties["addr:housenumber"]
                + "<br>" + feature.properties["addr:postcode"] + " " + feature.properties["addr:city"]
+ "<br>" + feature.properties["addr:place"];`

**Comment by dooley** [comment]
Ok, ich bin blind. Sorry, das habe ich tatsächlich übersehen.

**Comment by stefangrotz** [comment]
Passiert, fremder code ist immer eine schwierige Sache. 

Ich würde das Popup selbst mal in eine eigene .js und .css Datei auslagern und dann anfangen mir zu überlegen, ob man nicht unterschiedliches Verhalten für unterschiedliche Nodes haben möchte. Hast Du dazu Ideen?

**Comment by stefangrotz** [comment]
popup ist jetzt in popupcontent.js ausgelagert
