### ISSUE TITLE
vending=	eggs;potatoes;food

### ISSUE THREAD

**Issue by lintux** [CodeforKarlsruhe/direktvermarkter#32]
Hi,

kann es sein, daß POIs mit mehren Werten unter "vending=" nicht beachtet werden, auch wenn "food" Bestandteil der Liste ist?
Das sollte m.E funktionieren.
https://www.openstreetmap.org/node/5638001165

Gruß
Stephan (tux67)

**Comment by stefangrotz** [comment]
entscheident dafür ob ein Automat auf der Karte auftraucht  ist amenity=vending_machine 

Der Food Tag werden nur dafür verwendet die richtigen Automaten zu importieren.

**Comment by nachtgold** [comment]
Was fehlt https://www.openstreetmap.org/node/4328537874 um auf der Karte zu erscheinen?

attribute | value
-- | --
amenity | vending_machine
currency:EUR | yes
name | Eierautomat
payment:cash | yes
vending | eggs

**Comment by stefangrotz** [comment]
Hi nachtgold,

im Moment werden Automaten mit vending=eggs einfach nicht in die Daten importiert, weil die Lage sehr unklar ist. Siehe dafür z.B. diese Diskussion hier:
https://forum.openstreetmap.org/viewtopic.php?id=61802
https://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Dvending_machine

Ich wüsste auch nciht wie ich eine Query auf eine Tag mit mehreren Variablen schreiben sollte, hast Du da einen Tipp?

Das ist im Moment die Query:
```

[out:json][timeout:250];
  // gather results
  (
  // query part for: “vending=milk”
  node["vending"="milk"](${bbox});
  way["vending"="milk"](${bbox});
  relation["vending"="milk"](${bbox});
  // query part for: “shop=farm”
  node["shop"="farm"](${bbox});
  way["shop"="farm"](${bbox});
  relation["shop"="farm"](${bbox});
  // query part for: “vending=food”
  node["vending"="food"](${bbox});
  way["vending"="food"](${bbox});
  relation["vending"="food"](${bbox});
  // query part for: “amenity=marketplace”
  node["amenity"="marketplace"](${bbox});
  way["amenity"="marketplace"](${bbox});
  relation["amenity"="marketplace"](${bbox});
  );
  // print results
  out center;
`;
```

**Comment by nachtgold** [comment]
Interessante Diskussion.  Mit der Tilde (~) statt Gleichheitszeichen kannst du ein "contains" %Wunschwert% machen. Damit ist der Ausdruck im RegEx Mode und durch die Pipe (|) hängst du die verschiedenen Werte auch gleich an einander (erklärt in https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Key.2Fvalue_matches_regular_expression_.28.7E.22key_regex.22.7E.22value_regex.22.29):

`node["vending"~"milk|eggs|food"];out;`

Als Beispiel-Link: http://overpass-turbo.eu/s/zdg

**Comment by stefangrotz** [comment]
Interessant, das werde ich einbauen und dort möglichst viele Tags mitnehmen. Kennst Du zufälligerweise auch einen Weg statt der bbox eine query auf die drei Länder Deutschland, Schweiz und Österreich zu machen? Für einzelne Regionen geht es relativ einfach aber für mehrere Regionen habe ich noch keinen Weg gefunden.

**Comment by stefangrotz** [comment]
Okay eggs ist jetzt dabei, weitere Tags folgen noch.

**Comment by nachtgold** [comment]
Bzgl. der drei Länder: https://overpass-turbo.eu/s/ze9

Was hälst du von folgendem?
`rel["ISO3166-1"~"DE|CH|AT"];
(._;>;);
out;`

Wobei die mittlere Zeile nur zur Visualisierung drin ist und dann durch deine Node-Auswahl ersetzt wird.

**Comment by stefangrotz** [comment]
Interessant, werde ich mir anschauen, danke.
