### ISSUE TITLE
Wikipedia Layer

### ISSUE THREAD

**Issue by TZornG** [CodeforKarlsruhe/direktvermarkter#53]
Hallo, 

der Standard-Hintergrundlayer "Wikipedia Kartenstil"  lädt bei mir (und anderen, mit denen ich vor ein paar Wochen über die Karte gesprochen habe) in vielen Fällen nicht richtig. Einzelne Kachelanfragen bekommen einen Statuscode 429 zurückgeliefert. Das passiert schon beim ersten Aufrufen der Seite, mal sind mehr, mal weniger Kacheln betroffen, aber insgesamt ist dieser Layer für mich nicht nutzbar.

1. Kann das Problem behoben werden?
2. Könnte die Auswahl des Layers über Sitzungen hinweg gespeichert werden?
3. Könnte die Auswahl des Layers in der URL mitübergeben werden?

**Comment by stefangrotz** [comment]
Hi, danke für den HInweis. 

Ich wüsste nicht wie man das Problem beheben kann, hast Du eine Idee woran es scheitert? https://maps.wikimedia.org/ scheint auch Probleme zu haben.

Ich werde später die Standardkarte auf Openstreetmap umstellen. 

> Könnte die Auswahl des Layers in der URL mitübergeben werden?

Nein, bis jetzt ist das auch nicht als Feature geplant. Ich bin aber immer offen, falls jemand das Feature implementieren möchte.

**Comment by TZornG** [comment]
Es scheint, Wikimedia [blockiert Anfragen von Nicht-Wikimedia-Seiten absichtlich](https://phabricator.wikimedia.org/T245145). Ich denke, du solltest diesen Hintergrund rausnehmen. Wenn dir Standard-OSM nicht gefällt, gibt es vielleicht noch andere freie Kartenhintergründe. Kommt vermutlich auch stark drauf an, wieviele Anfragen diese Webseite im Monat stellt.  [Maptiler](https://www.maptiler.com/cloud/plans/) wäre möglicherweise eine Alternative, aber sicher gibt es auch noch andere. Ich hab nur kurz gegoogelt.

**Comment by stefangrotz** [comment]
Ich habe in f09213d vorerst die Wikipedia-Karte gelöscht. Schade, ich mag den Stil sehr viel mehr als den der Openstreetmap Karte, vielleicht suche ich irgendwann noch eine schöne neue Standard Karte heraus.

Danke für den Hinweis!
